src/pages/urls.py
from django.urls import path
from . import views
from tcgplaya.views import ajax_cart_request
from pages.views import ChangePasswordView
from django.conf.urls import include, url


# pages url configuration
app_name = 'pages'
urlpatterns = [
    path('', views.home_view, name = ''),
    path('home/', views.home_view, name = 'home'),
    path('login/', views.login_view, name = 'login'),
    path('register/', views.register_view, name = 'register'),
    path('profile/', views.profile_view, name = 'profile'),
    path('cart/', views.cart_view, name = 'cart'),
    path('change-password/', ChangePasswordView.as_view(), name='change_password'),
    path('home_searched/', views.home_searched, name = 'home-searched'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('add_to_cart', ajax_cart_request)
]

src/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('cards/', include('tcgplaya.urls')),
]

src/tcgplaya/urls.py
from django.urls import path
from . import views

# tcgplaya url configuration
app_name = 'tcgplaya'
urlpatterns = [
    path('card/<int:id>', views.card_view),
    path('cardlistings/', views.cardlistings_view),
    path('cardlisting/<int:id>', views.cardlisting_view),
    path('new-cardlisting/<int:id>', views.new_cardlisting_view),    
    path('cardlistings_searched/', views.cardlistings_searched),
    path('my-listings/', views.my_listings_view)
]

src/tcgplaya/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# TODO: update which fields need to be mandatory, etc

# format price Decimal Fields
price_kwargs = dict(
    default=0.0, decimal_places=2, max_digits=6,
    blank=True, null=True)

class Card(models.Model):
    '''
    Card based on some of Scryfall's MTG card fields.
    '''
    # e.g. '0000579f-7b35-4ed3-b44c-db2a538066fe'
    card_id = models.CharField(default='', max_length=36)
    name = models.CharField(default='', max_length=256)
    # this card's set
    cardset = models.ForeignKey('CardSet', null=True, default=None,
                                on_delete=models.CASCADE)

    # e.g. 'uncommon', 'common', 'rare', 'mythic', 'special', 'bonus'
    rarity = models.CharField(default='', max_length=8)

    # the prices available for this card
    usd = models.DecimalField(**price_kwargs)
    usd_foil = models.DecimalField(**price_kwargs)
    usd_etched = models.DecimalField(**price_kwargs)
    eur = models.DecimalField(**price_kwargs)
    eur_foil = models.DecimalField(**price_kwargs)
    tix = models.DecimalField(**price_kwargs)

    released_at = models.DateField(blank=True, null=True)

    # used for getting image url e.g. https://c1.scryfall.com/file/scryfall-cards/normal/front/b/e/be72ff91-f810-46c3-884f-6e65827824bc.jpg?1598917660
    img_uri = models.CharField(default='', max_length=100)

    # e.g. '{X}{W} // {2}{R} // {2}{U} // {3}{B} // {1}{G}', '{5}{R}'
    mana_cost = models.CharField(default='', max_length=46)
    # e.g. 6.0, max: 1000000.0
    cmc = models.DecimalField(default=0, decimal_places=1, max_digits=8,
                              blank=True, null=True)
    # e.g. 'Creature — Siren Pirate'
    type_line = models.CharField(default='', max_length=80)
    # ability of the card. max len is 769
    oracle_text = models.CharField(default='', max_length=800)
    
    # e.g. '3', '', '*', '-1', '1+*', '?', '.5'
    power = models.CharField(default='', max_length=3)
    toughness = models.CharField(default='', max_length=3)
    # e.g. "['B', 'R']", max len: "['B', 'G', 'R', 'U', 'W']"
    colors = models.CharField(default='', max_length=25)
    # e.g. ['Landwalk', 'Flanking', 'Fading'], maxlen: 124
    keywords = models.CharField(default='', max_length=128)

    # adds character to the card, usually a moto or a tagline. max: 448
    flavor_text = models.CharField(default='', max_length=500)
    # whether or not this card was part of a booster or not
    booster = models.BooleanField(default=False)
    # some rank (not always available)
    edhrec_rank = models.DecimalField(default=0, decimal_places=1, max_digits=8,
                                      blank=True, null=True)
    # card language
    lang = models.CharField(default='', max_length=20)


    # string representation of self
    def __str__(self):
        return self.name

    def __repr__(self):
        return str(self)

class CardSet(models.Model):
    '''
    Cards can be part of a card set
    '''
    # e.g. 'c1d109bc-ffd8-428f-8d7d-3f8d7e648046'
    set_id = models.CharField(default='', max_length=256)
    # e.g. 'tsp'
    set_codename = models.CharField(default='', max_length=256)
    # e.g. 'Time Spiral'
    set_name = models.CharField(default='', max_length=256)
    # e.g. expansion, core, token
    set_type = models.CharField(default='', max_length=256)
    
    # string representation of self
    def __str__(self):
        return self.set_name

    def __repr__(self):
        return str(self)

class CardListing(models.Model):
    '''
    Represents a user selling a card
    '''
    # the card that this listing is for
    card = models.ForeignKey('Card', null=True, default=None,
                             on_delete=models.CASCADE)
    # the user that is selling the card(s)
    seller = models.ForeignKey('Profile', related_name='seller',
                               on_delete=models.CASCADE)
    # the price of the card
    price = models.DecimalField(default=0, decimal_places=2, max_digits=6)
    # the listed quantity of the card being listed
    quantity = models.IntegerField(default=0)
    # the buyer (if null, the card(s) has not been bought yet)
    buyer = models.ForeignKey('Profile', null=True, related_name='buyer', blank=True,
                              on_delete=models.CASCADE)
    
    # string representation of self
    def __str__(self):
        return f'CardListing(card={self.card}, seller={self.seller}, price={self.price})'

    def __repr__(self):
        return str(self)


#######################################################
# USERS
#######################################################

class Profile(models.Model):
    '''
    User profile: extension of django.contrib.auth.model.User
    '''
    # the user this profile is for
    user = models.OneToOneField(User, related_name="profile", on_delete=models.CASCADE)
    # the user's username
    username = models.TextField(default='')
    # user cart
    cart = models.ManyToManyField('CardListing')
    
    # string representaion of self
    def __str__(self):
        cart = [ cardlisting.card.name for cardlisting in self.cart.all() ]
        return f'Profile(user={self.user}, email={self.user.email}, cart={cart})'
    
    def __repr__(self):
        return str(self)

# if the user is created, a profile is created as well
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    
# when the user is saved, their profile is saved as well
@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

src/tcgplaya/views.py
from django.http.response import JsonResponse
from django.shortcuts import redirect, render
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt

from .models import *
from django.contrib.auth.models import User

# single card view
def card_view(request, id):
    context = {}
    card = Card.objects.get(id=id)
    listings = CardListing.objects.filter(card=card)
    listings = listings.order_by('price')

    context = dict(
        card = card,
        listings=listings
    )

    return render(request, 'tcgplaya/card.html', context)


# cardlistings page search bar
def cardlistings_searched(request):
    if request.method == "POST":
        searchedL = request.POST['searchedL']
        listings = CardListing.objects.all()

        # get all listings whose cards contain searched word
        matched_search_listings = []
        for listing in listings:
            if searchedL.lower() in listing.card.name.lower():
                matched_search_listings.append(listing)

        # return empty dict if no matches found
        if not matched_search_listings:
            return render(request, 'tcgplaya/cardlistings_searched.html', {})

        context = {
            'searchedL': searchedL,
            'listings': matched_search_listings
        }
        return render(request, 'tcgplaya/cardlistings_searched.html', context)
        
    return render(request, 'tcgplaya/cardlistings_searched.html', {})

# multiple cardlistings page
def cardlistings_view(request):
    context = {}
    listings = CardListing.objects.all()
    context = dict(
        listings=listings
    )

    return render(request, 'tcgplaya/cardlistings.html', context)

# a single cardlisting for a card
def cardlisting_view(request, id):
    listing = CardListing.objects.get(id=id)
    in_cart, seller = 'no', False
    if request.user.username:
        # redirect user to register page if not logged in
        profile = Profile.objects.get(user = request.user)

        # check if cardlisting in cart
        cart = profile.cart.all()
        for cart_listing in cart:
            print(cart_listing)
            if cart_listing.id == id:
                in_cart = 'yes'
                break
        
        # check if user is the seller of the cardlisting
        if profile == listing.seller:
            seller = True
            in_cart = 'seller'

    context = {
        'listing': listing,
        'in_cart': in_cart,
        'seller': seller,
        'user': request.user,
    }

    return render(request, 'tcgplaya/cardlisting.html', context)

@csrf_exempt
def ajax_cart_request(request):
    id = request.POST.get('id')
    listing = CardListing.objects.get(id=id)
    in_cart = 'no'
    if request.user:
        # redirect user to register page if not logged in
        profile = Profile.objects.get(user = request.user)

        # check if cardlisting in cart
        cart = profile.cart.all()
        for cart_listing in cart:
            print(cart_listing)
            if cart_listing.id == id:
                in_cart = 'yes'
                break
        
        # check if user is the seller of the cardlisting
        if profile == listing.seller:
            in_cart = 'seller'
    
    if request.method == "POST":
        if request.user:
            # add and remove from cart, delete listing
            if request.POST.get('add_cart'):
                print("adding cardlisting")
                in_cart = 'yes'
                profile.cart.add(listing)
            elif request.POST.get('remove_cart'):
                print("removing cardlisting")
                in_cart = 'no'
                profile.cart.remove(listing)
            elif request.POST.get('delete_listing'):
                print("deleting listing")
                listing.delete()
                return redirect('/cards/cardlistings/')
        else:
            return redirect('/register/')

    context = {
        'in_cart': in_cart,
    }
    print(context)
    return JsonResponse(context)

# create a new cardlisting from a given card
def new_cardlisting_view(request, id):
    if not request.user.username:
        # redirect user to register page if not logged in
        return redirect('/register/')

    context = {}
    if request.method == "POST":
        listing_price = request.POST.get('listing_price')
        print(f"listing price: {listing_price}")
        # create new cardlisting
        card = Card.objects.get(id=id)
        seller_profile = Profile.objects.get(user = request.user)
        if listing_price:
            cardlisting = CardListing.objects.create(
                card=card,
                seller=seller_profile,
                price=listing_price
            )
            print("new cardlisting created: ", cardlisting)
            return redirect(f'/cards/card/{id}')
        else:
            print("new cardlisting not created")


        context = {
            'card': card,
            'suggest_price': card.usd,
            'listing_price': listing_price,
        }
    return render(request, 'tcgplaya/new_cardlisting.html', context)

# user's own listings view
def my_listings_view(request):
    if not request.user.username:
        # redirect user to register page if not logged in
        return redirect('/register/')

    profile = Profile.objects.get(user = request.user)
    # get user's saved card listings
    my_listings = []
    listings = CardListing.objects.all()
    for listing in listings:
        if listing.seller == profile:
            my_listings.append(listing)
    context = {
        'listings': my_listings
    }
    return render(request, 'tcgplaya/my_listings.html', context)

src/tcgplaya/templates/tcgplaya/card.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <div class="row justify-content-center ">
        <div class="col-lg-10">
            <div class="card light-gray-border shadow-lg rounded-lg mt-0 mb-3 animate__animated animate__zoomIn animate__faster">
                <div class="card-header justify-content-center">
                    <h2 class="font-weight-light my-4 text-center">
                        {{ card.name }}
                    </h2>
                    <h6 class="font-weight-light my-4 text-center">Card</h6>
                </div><br>
                <div class="card-listing">
                    <div
                        class="card-container justify-content-center animate__animated animate__bounceIn animate__fast delay-anim">
                        {% comment %} big column 1 {% endcomment %}
                        <div class="col">
                            <div class="order-md-first bg-white">
                                <img class="img-fluid mx-auto d-block" width="300px" alt="Responsive image"
                                    src="{{ card.img_uri }}">
                            </div>
                        </div>
                    </div>
                    <br>
                    <div class="card-details-container animate__animated animate__bounceIn delay-anim">
                        <div class="card-information-container">
                            {% comment %} top row details {% endcomment %}
                            <div class="card text-black bg-muted card-info "
                                style="width: 100%">
                                <div class="card-header">
                                    <i class="bi bi-info-circle"></i>
                                    <span class="font-weight-light my-4 info-header" style="font-size: 1.2rem;">Card Information</span>
                                </div>
                                <div class="card-body">
                                    {% if card.oracle_text or card.rarity or card.card_set%}
                                    <div>
                                        {% comment %} card details {% endcomment %}
                                        {% if card.oracle_text %}
                                        <p><strong>Oracle text: </strong>{{ card.oracle_text }}</p>
                                        {% else %}
                                        <p><strong>Oracle text: </strong>No oracle text available for this card.</p>
                                        {% endif %}
                                    </div>
                                    <div>
                                        {% if card.rarity %}
                                        <p><strong>Rarity: </strong>{{ card.rarity }}</p>
                                        {% else %}
                                        <p><strong>Rarity: </strong>No rarity available for this card.</p>
                                        {% endif %}
                                    </div>
                                    <div>
                                        {% if card.card_set %}
                                        <p><strong>Set: </strong>{{ card.card_set }}</p>
                                        {% else %}
                                        <p><strong>Set: </strong>No set available for this card.</p>
                                        {% endif %}
                                    </div>
                                    {% else %}
                                    <div>
                                        <p>No additional information available about this card</p>
                                    </div>
                                    {% endif%}
                                </div>
                                <div class="card-more-info-button">
                                    <button class="btn btn-outline-secondary" type="button" data-toggle="collapse"
                                        data-target="#collapseExample" aria-expanded="false"
                                        aria-controls="collapseExample">
                                        More information
                                    </button>
                                </div>
                                <div class="collapse" id="collapseExample">
                                    <div class="card card-body">
                                        {% if card.flavor_text %}
                                        <p><strong>Flavour text: </strong>{{ card.flavor_text }}</p>
                                        {% endif %}

                                        {% if card.released_at %}
                                        <p><strong>Release Date: </strong>{{ card.released_at }}</p>
                                        {% endif %}

                                        {% if card.type_line %}
                                        <p><strong>Type: </strong>{{ card.type_line }}</p>
                                        {% endif %}

                                        {% if card.edhrec_rank %}
                                        <p><strong>Popularity Ranking: </strong>{{ card.edhrec_rank }}</p>
                                        {% endif %}

                                        {% if card.mana_cost %}
                                        <p><strong>Mana Cost: </strong>{{ card.mana_cost }}</p>
                                        {% endif %}

                                        {% if card.cmc %}
                                        <p><strong>Converted Mana Cost (CMC): </strong>{{ card.cmc }}</p>
                                        {% endif %}

                                        {% if card.power %}
                                        <p><strong>Power: </strong>{{ card.power }}</p>
                                        {% endif %}

                                        {% if card.toughness %}
                                        <p><strong>Toughness: </strong>{{ card.toughness }}</p>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                            <br>
                            {% comment %} bottom row cardlistings {% endcomment %}
                            <div class="card card-listings-container text-black bg-muted"
                                style="width: 100%">
                                <div class="card-header">
                                    <i class="bi bi-list" style="font-size: 1.2rem;"></i>
                                    <span class="font-weight-light my-4 info-header">Card Listings</span>
                                </div>
                                <div class="card-body">
                                    {% if listings %}
                                    <ul>
                                        {% for listing in listings %}
                                        <li><a href='/cards/cardlisting/{{ listing.id }}'>{{ listing.seller.user|title }}: ${{listing.price }}</a>
                                        {% endfor %}
                                    </ul>
                                    {% else %}
                                    <p>No cardlistings available for this card.</p>
                                    {% endif %}
                                </div>
                                <div class="cardlisting-submit-button">
                                    <form class="form-inline my-2 my-lg-0 ml-auto justify-content-end" method="POST"
                                        action="/cards/new-cardlisting/{{ card.id }}">
                                        {% csrf_token %}
                                        <button class="btn btn-secondary my-2 my-sm-0 " type="submit"><i class="bi bi-plus-square" style="font-size: 1rem;"></i> <span>Add
                                            Cardlisting</span></button>
                                    </form>
                                </div>
                            </div>
                            <br>
                        </div>
                    </div>
                </div>
                <br>
            </div>
        </div>
    </div>
</div>

<script>
    let delay_duration = 10000;
    $('#add-to-cart-btn').on('click', () => {
        $('#tmsg').toast({autohide: false, animation: false});
        $('#tmsg').toast('show');
        $('#tmsg').css('display', 'block');

        setTimeout(() => {
            $('#tmsg').css('display', 'none');
        }, delay_duration);
    });
</script>


{% endblock %}

src/tcgplaya/templates/tcgplaya/cardlistings.html
{% extends 'base.html' %}
{% comment %} This is the Card Listing page (with all the card listings) {% endcomment %}

{% block content %}
<h1>Marketplace</h1>
{% if listings %}
<form class="form-inline justify-content-center" method="POST" action="/cards/cardlistings_searched/">
  {% csrf_token %}
  <input class="form-control mr-sm-2" type="search" placeholder="Search Listing..." aria-label="Search"
    name="searchedL">
  <button class="btn btn-secondary" type="submit">Search</button>
</form>
{% comment %} This displays a list of cards listings with links to the card listings view {% endcomment %}
<br>
<div class="cards-list-container justify-content-center" style="display: grid">
  <div class="row" style="width: 90vw;">
    {% for listing in listings %}
    {% if forloop.counter|divisibleby:"4" %}
    <div class="col-sm animate__animated animate__zoomIn animate__faster">
      <a class="card-link-list" href='/cards/cardlisting/{{ listing.id }}'>
        <span class="card-title-list mx-auto">{{ listing.card.name }} @ ${{ listing.price }} </span>
        <img class="img-fluid mx-auto d-block card-img-list" src="{{ listing.card.img_uri }}">
      </a>
    </div>
  </div>
  <br>
  {% if not forloop.last %}
  <div class="row" style="width: 90vw;">
    {% endif %}
    {% else %}
    <div class="col-sm animate__animated animate__zoomIn animate__faster">
      <a class="card-link-list" href='/cards/cardlisting/{{ listing.id }}'>
        <span class="mx-auto card-title-list">{{ listing.card.name }} @ ${{ listing.price }} </span>
        <img class="img-fluid mx-auto d-block card-img-list" src="{{ listing.card.img_uri }}">
      </a>
    </div>
    {% endif %}
    {% endfor %}
  </div>
{% else %}
</br>
<h5>Seems like there are no card listings yet... Let's do something about that ;)</h5>

{% endif %}
{% endblock %}

src/tcgplaya/templates/tcgplaya/cardlistings_searched.html
{% extends 'base.html' %}
{% comment %} This is the Card Listing page (with all the card listings) {% endcomment %}

{% block content %}

<center>
    <form class="form-inline justify-content-center" method="POST" action="/cards/cardlistings_searched/">
        {% csrf_token %}
        <input class="form-control mr-sm-2" type="search" placeholder="Search Listing..." aria-label="Search"
            name="searchedL">
        <button class="btn btn-secondary" type="submit">Search</button>
    </form>
    <br>
    {% if searchedL %}
    {% comment %} This displays a list of cards listings with links to the card listings view {% endcomment %}
    <br>
    <div class="cards-list-container justify-content-center" style="display: grid">
        <div class="row" style="width: 90vw;">
            {% for listing in listings %}
            {% if forloop.counter|divisibleby:"4" %}
            <div class="col-sm animate__animated animate__zoomIn animate__faster">
                <a class="card-link-list" href='/cards/cardlisting/{{ listing.id }}'>
                    <span class="card-title-list mx-auto">{{ listing.card.name }} @ ${{ listing.price }} </span>
                    <img class="img-fluid mx-auto d-block card-img-list" src="{{ listing.card.img_uri }}">
                </a>
            </div>
        </div>
        <br>
        {% if not forloop.last %}
        <div class="row" style="width: 90vw;">
            {% endif %}
            {% else %}
            <div class="col-sm animate__animated animate__zoomIn animate__faster">
                <a class="card-link-list" href='/cards/cardlisting/{{ listing.id }}'>
                    <span class="mx-auto card-title-list">{{ listing.card.name }} @ ${{ listing.price }} </span>
                    <img class="img-fluid mx-auto d-block card-img-list" src="{{ listing.card.img_uri }}">
                </a>
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% else %}

        <h1> No search results found. </h1>

        {% endif %}
</center>
{% endblock %}

src/tcgplaya/templates/tcgplaya/my_listings.html
{% extends 'base.html' %}
{% comment %} All the user's card listings (cards they have made for sale) {% endcomment %}

{% block content %}
<h1>My Card Listings</h1>
{% if listings %}
<div class="cards-list-container justify-content-center" style="display: grid">
  <div class="row" style="width: 90vw;">
    {% for listing in listings %}
    {% if forloop.counter|divisibleby:"4" %}
    <div class="col-sm animate__animated animate__zoomIn animate__faster">
      <a class="card-link-list" href='/cards/cardlisting/{{ listing.id }}'>
        <span class="card-title-list mx-auto">{{ listing.card.name }}: ${{ listing.price }} </span>
        <img class="img-fluid mx-auto d-block card-img-list" src="{{ listing.card.img_uri }}">
      </a>
    </div>
  </div>
  <br>
  {% if not forloop.last %}
  <div class="row" style="width: 90vw;">
    {% endif %}
    {% else %}
    <div class="col-sm animate__animated animate__zoomIn animate__faster">
      <a class="card-link-list" href='/cards/cardlisting/{{ listing.id }}'>
        <span class="mx-auto card-title-list">{{ listing.card.name }}: ${{ listing.price }} </span>
        <img class="img-fluid mx-auto d-block card-img-list" src="{{ listing.card.img_uri }}">
      </a>
    </div>
    {% endif %}
    {% endfor %}
  </div>

{% else %}
  </br>
    <h5>Seems like you have not uploaded any listings yet... Let's do something about that ;)</h5>
{% endif %}

{% endblock %}

src/tcgplaya/templates/tcgplaya/new_cardlisting.html
{% extends "base.html" %}
{% comment %} User add new card listing to sell {% endcomment %}

{% block content %}
<div class="container">
    <div class="row justify-content-center ">
        <div class="col-lg-10">
            <div class="card light-gray-border shadow-lg rounded-lg mt-0 mb-3 animate__animated animate__zoomIn animate__faster">
                <div class="card-header justify-content-center">
                    <h2 class="font-weight-light my-4 text-center">
                        {{ card.name }}
                    </h2>
                    <h6 class="font-weight-light my-4 text-center">Add new Card Listing</h6>
                </div><br>
                <div class="card-listing">
                    <div
                        class="card-container justify-content-center animate__animated animate__bounceIn animate__fast delay-anim">
                        {% comment %} Image {% endcomment %}
                        <div class="col">
                            <div class="order-md-first bg-white my-4">
                                <img class="img-fluid mx-auto d-block" width="300px" alt="Responsive image"
                                    src="{{ card.img_uri }}">
                            </div>
                        </div>
                    </div>
                    <br>
                    <div class="card-details-container animate__animated animate__bounceIn delay-anim">
                        <div class="card-information-container">
                            {% comment %} top row details {% endcomment %}
                            <div class="card text-black bg-muted card-info "
                                style="width: 100%">
                                <div class="card-header">
                                    <i class="bi bi-info-circle"></i>
                                    <span class="font-weight-light my-4 info-header" style="font-size: 1.2rem;">Card Price</span>
                                </div>
                                <div>
                                    <form class="form-inline my-2 my-lg-3 ml-auto justify-content-center" method="POST">
                                        {% csrf_token %}
                                        $<input class="form-control mr-sm-2" type="number" step="0.01" value = {{ suggest_price }} placeholder="Enter price..." name="listing_price">
                                        <button class="btn btn-secondary my-2 my-sm-2 " type="submit"><i class="bi bi-plus-square" style="font-size: 1rem;"></i> <span>Add new listing</span></button>
                                    </form>
                                </div>
                                
                                <div class = "extra-text">
                                    {% if suggest_price %}
                                    Market price is currently ${{ suggest_price }}.
                                    {% else %}
                                    No market price available for this card.
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <br>
            </div>
        </div>
    </div>
</div>

<script>
    let delay_duration = 10000;
    $('#add-to-cart-btn').on('click', () => {
        $('#tmsg').toast({autohide: false, animation: false});
        $('#tmsg').toast('show');
        $('#tmsg').css('display', 'block');

        setTimeout(() => {
            $('#tmsg').css('display', 'none');
        }, delay_duration);
    });
</script>


{% endblock %}